### ISSUE TITLE
Rats are added by Rats, not Alex's Mobs

### ISSUE THREAD

**Issue by StrangerSon71** [infernalexp/Arthropod-Expansion#2]
Title.

**Comment by SwanX1** [comment]
what

**Comment by StrangerSon71** [comment]
On the wiki, it says ladybugs are hostile to rats from Alex’s Mobs. Alex’s Mobs doesn’t add rats, Rats by the same developer does.

**Comment by SwanX1** [comment]
This isn't really the place to report this.

**Comment by StrangerSon71** [comment]
I don't use discord, where do you recommend I report this?

**Comment by SwanX1** [comment]
On [our discord](https://infernalstudios.org/discord).

**Comment by StrangerSon71** [comment]
As stated, I don't use discord. I give up.
